name: 'Deployer action Magento 2'
description: 'Deployer configuration for deploy Magento 2 with zero down-time'
author: 'Misha Serbenyuk'
branding:
  color: yellow
  icon: package
inputs:
  php_version:
    description: 'Versions of php will be used'
    default: '7.4'
  task: 
    description: 'Task to run, example build, deploy, docker'
    required: true
  target:
    description: 'Where run deploy, used only if deploy to server'
  extra_arguments:
    description: 'Extra arguments for deployer, like verbose mode'

runs:
  using: 'composite'
  steps:
     - uses: 'docker://ghcr.io/qlicks/magento-deployer:0.0.2'
     env: 
        INPUT_PHP_VERSION: ${{ inputs.php_version }}
        INPUT_TASK: ${{ inputs.task }}
        INPUT_TARGET: ${{ inputs.target }}
        INPUT:EXTRA_ARGUMENTS: ${{ inputs.extra_arguments }}
