name: 'Deployer action Magento 2'
description: 'Deployer configuration for deploy Magento 2 with zero down-time'
author: 'Misha Serbenyuk'
branding:
  color: yellow
  icon: package
inputs:
  php-version:
    description: 'Versions of php will be used'
    required: true
  task: 
    description: 'Task to run, example build, deploy, docker'
    required: true
  target:
    description: 'Where run deploy, used only if deploy to server'
  extra-arguments:
    description: 'Extra arguments for deployer, like verbose mode'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/mad-i-t/magento-actions:3.3.1'
  args: 
    - ${{ inputs.task }}
    - ${{ inputs.target }}
    - ${{ inputs.extra-arguments }}