name: 'Deployer action Magento 2'
description: 'Deployer configuration for deploy Magento 2 with zero down-time'
author: 'Misha Serbenyuk'
branding:
  color: yellow
  icon: package
inputs:
  php_version:
    description: 'Versions of php will be used'
    default: '7.4'
  task: 
    description: 'Task to run, example build, deploy, docker'
    required: true
  target:
    description: 'Where run deploy, used only if deploy to server'
  extra_arguments:
    description: 'Extra arguments for deployer, like verbose mode'
  slack_channel:
    description: 'Slack channel id to inform (optional)'

runs:
  using: 'composite'
  steps:
     - id: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

     - id: get_enviroment_variables
       uses: FranzDiebold/github-env-vars-action@v2

     - id: start_notification
       uses: qlicks/deployer-action/action-slack@master
       with:
          text: 'Task ${{ inputs.task }} on ${{ inputs.target }} start'
          status: ${{ job.status }}
          channel: ${{ inputs.slack_channel }}
          fields: repo,message,commit,author,eventName,ref # selectable (default: repo,message)

     - id: composer-cache
       run: |
            export HOME=/root
            echo "::set-output name=dir::$(composer config cache-files-dir)"
       shell: bash
     - uses: actions/cache@v2
       with:
           path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: |
                 ${{ runner.os }}-composer-
     - id: deloyer_action
       uses: 'docker://ghcr.io/qlicks/magento-deployer:0.0.3'
       env: 
          INPUT_PHP_VERSION: ${{ inputs.php_version }}
          INPUT_TASK: ${{ inputs.task }}
          INPUT_TARGET: ${{ inputs.target }}
          INPUT_EXTRA_ARGUMENTS: ${{ inputs.extra_arguments }}
          
          
