name: 'Deployer action Magento 2'
description: 'Deployer configuration for deploy Magento 2 with zero down-time'
author: 'Misha Serbenyuk'
branding:
  color: yellow
  icon: package
inputs:
  php_version:
    description: 'Versions of php will be used'
    default: '7.4'
  task: 
    description: 'Task to run, example build, deploy, docker'
    required: true
  target:
    description: 'Where run deploy, used only if deploy to server'
  extra_arguments:
    description: 'Extra arguments for deployer, like verbose mode'
  slack_channel:
    description: Slack channel id to inform

runs:
  using: 'composite'
  steps:
     - id: get_enviroment_variables
       uses: FranzDiebold/github-env-vars-action@v2
     - id: notification
       uses: ${{ github.action_path }}/action-slack
       with:
          text: 'Start build and deploy'
          status: ${{ job.status }}
          channel: ${{ inputs.slack_channel }}
          fields: repo,message,commit,author,ref # selectable (default: repo,message)
      
     - id: deloyer_action
       uses: 'docker://ghcr.io/qlicks/magento-deployer:0.0.2'
       env: 
          INPUT_PHP_VERSION: ${{ inputs.php_version }}
          INPUT_TASK: ${{ inputs.task }}
          INPUT_TARGET: ${{ inputs.target }}
          INPUT_EXTRA_ARGUMENTS: ${{ inputs.extra_arguments }}
