name: 'Deployer action Magento 2'
description: 'Deployer configuration for deploy Magento 2 with zero down-time'
author: 'Misha Serbenyuk'
branding:
  color: yellow
  icon: package
inputs:
  php_version:
    description: 'Versions of php will be used'
    default: '7.4'
  task: 
    description: 'Task to run, example build, deploy, docker'
    required: true
  target:
    description: 'Where run deploy, used only if deploy to server'
  extra_arguments:
    description: 'Extra arguments for deployer, like verbose mode'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/qlicks/magento-deployer:latest'
  args: 
    - ${{ inputs.php_version }}
    - ${{ inputs.task }}
    - ${{ inputs.target }}
    - ${{ inputs.extra_arguments }}